// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBem5v0uhEpj2E3ujWtAnB4re1usjtgHL8',
    appId: '1:344757706040:web:c1d90e2660eb108528f5cd',
    messagingSenderId: '344757706040',
    projectId: 'kwartx',
    authDomain: 'kwartx.firebaseapp.com',
    storageBucket: 'kwartx.firebasestorage.app',
    measurementId: 'G-MLVWJKZBN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCne_6k8aZuOeiJe-iYw6vXpHIYRSH6c3w',
    appId: '1:344757706040:android:b9b8b9f52d4ab05528f5cd',
    messagingSenderId: '344757706040',
    projectId: 'kwartx',
    storageBucket: 'kwartx.firebasestorage.app',
  );
}
